import Head from 'next/head'
import Image from 'next/image'
import {useState} from "react"
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import HomeBanner from '@/components/Home/HomeBanner'

import {  Typography } from '@mui/material';

import { AddIcon } from '@chakra-ui/icons'
import { Box } from '@mui/system'
import FAQ from '@/components/Home/FAQ'
import Courses from './../components/Home/Courses';
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  let [val,setVal] = useState(false)
  const handle = ()=>{
    val?setVal(false):setVal(true)
  }


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css" rel="stylesheet"/>
        <link rel="stylesheet"
  href="https://unpkg.com/boxicons@latest/css/boxicons.min.css"/>

  <link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com"/>
<link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,600;0,700;1,600&display=swap" rel="stylesheet"/>

      </Head>
      
      {/* <div className={styles.main}> */}
    {/* <h1 className={styles.title}>User Profile's <a href='/'>Application</a> </h1> */}
      {/* </div> */}
      <HomeBanner/>
     <FAQ/>
     <Courses/>
      {/* <UsersList users={[]}/> */}
    </>
  )
}

// export async function getStaticProps(){
  // const res = await fetch('https://jsonplaceholder.typicode.com/users')
  // const users = await res.json()
  // return {
  //   props:{
  //     users
  //   }
  // }
    // const res = document.querySelectorAll('.faq');
    // faq.forEach(faq=>{
    //   faq.addEventListener("click",()=>{
    //     faq.classList.toggle('open')
    //   })
    // })
// }
